# Generated by Django 5.2.11 on 2026-03-02 08:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('status_change', 'Status change'), ('deactivate', 'Deactivate'), ('hold', 'Hold'), ('confirm', 'Confirm'), ('cancel', 'Cancel'), ('file_upload', 'File upload')], db_index=True, max_length=32)),
                ('entity', models.CharField(db_index=True, max_length=64)),
                ('entity_id', models.CharField(db_index=True, max_length=128)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('ts', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-ts'],
                'indexes': [models.Index(fields=['entity', 'entity_id', 'ts'], name='audit_audit_entity_56f693_idx'), models.Index(fields=['actor', 'ts'], name='audit_audit_actor_i_7287d8_idx'), models.Index(fields=['action', 'ts'], name='audit_audit_action_2478a6_idx')],
            },
        ),
    ]
