# Generated by Django 5.2.11 on 2026-02-28 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_ends_at_booking_starts_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='ends_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='starts_at',
            field=models.DateTimeField(),
        ),
    ]
