# Generated by Django 5.2.11 on 2026-03-02 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_ends_at_alter_booking_starts_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('archived', 'Archived')], db_index=True, default='pending', max_length=20),
        ),
    ]
