# Generated by Django 6.0.2 on 2026-02-09 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('duration', models.PositiveIntegerField(help_text='Длительность урока в минутах')),
                ('capacity', models.PositiveIntegerField(default=1, help_text='Максимальное количество учеников в слоте')),
                ('file_path', models.CharField(blank=True, max_length=512, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Если False, урок скрыт из поиска')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LessonSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('held', 'Held'), ('booked', 'Booked')], default='available', max_length=10)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='lessons.lesson')),
            ],
            options={
                'ordering': ['starts_at'],
                'indexes': [models.Index(fields=['starts_at', 'ends_at'], name='lessons_les_starts__f17388_idx'), models.Index(fields=['status'], name='lessons_les_status_6701bf_idx')],
                'constraints': [models.UniqueConstraint(fields=('lesson', 'starts_at'), name='unique_lesson_start'), models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='check_end_after_start')],
            },
        ),
    ]
