# Generated by Django 6.0.2 on 2026-02-11 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='lessonslot',
            name='lessons_les_starts__f17388_idx',
        ),
        migrations.AddIndex(
            model_name='lessonslot',
            index=models.Index(fields=['lesson', 'starts_at'], name='lessons_les_lesson__65c80d_idx'),
        ),
    ]
