# Generated by Django 5.2.11 on 2026-02-26 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_remove_lessonslot_lessons_les_starts__f17388_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonslot',
            name='held_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='held_slots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lessonslot',
            name='held_until',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='lessonslot',
            index=models.Index(fields=['held_until'], name='lessons_les_held_un_19a210_idx'),
        ),
    ]
